####Inputs####
#set working directory
setwd("~/todd/Expression_analysis")

##load bait lookups for ENSMBL gene IDs as generated by Bait_lookup_files.R
ENSMBL_look=read.delim("~/todd/Data/PCHiC/bait_ENSMBL_genes_look.txt",h=F)

##load Gingeras FPKM values as downloaded by download_ENCODE_RNA.R
ging.exp=read.delim("~/todd/Data/RNAseq/ENCODE_Gingeras_FPKM_values.txt")

##Predefined tissues which will be analysing and order for later plotting
ging.order=read.delim("Gingeras_order.txt",h=F)

##FPKM values from Cambuli et al which have not been log trasnformed
x=read.delim("~/todd/Data/RNAseq/Cambuli_RNA_FPKM_nolog.txt.txt")

#Lookup file for combining ENSMBL IDs and RefSeq IDS
cross.look=read.delim("~/todd/Data/Annotations/ENSMBL_Refseq_cross_lookup.txt")

#load R packages
library(ggplot2)

##HiC ROI-Gene interaction outputs from Pairing_Gothic_Data_to_Expression.R
es.gene.look=read.delim("~/todd/Data/Output/ES_gothic_gene_lookup.txt")
ts.gene.look=read.delim("~/todd/Data/Output/TS_gothic_gene_lookup.txt")


####Script####
colnames(ENSMBL_look)=c("Bait_ID","ENSMBL_ID")

##Removing the ES and TS datasets from order which will be added later
ging.order=ging.order[3:nrow(ging.order),]

##calculating the tissue means 
mean.df=data.frame(Gene=ging.exp[,1])
for(i in 1:length(ging.order)){
  tissue=ging.order[i]
  tissue.cols=grep(pattern=tissue,x = colnames(ging.exp))
  exp.means=rowMeans(ging.exp[,tissue.cols])
  mean.df[,i+1]=exp.means
  colnames(mean.df)[i+1]=as.character(tissue)
  }


##Format ENSMBL IDs
mean.df[,1]=unlist(lapply(strsplit(as.character(mean.df$Gene),split = "\\."),function(x){x[1]}))
colnames(mean.df)[1]="ENSMBL_ID"
#log transforn the expression data
mean.df[,2:ncol(mean.df)]=log2(mean.df[,2:ncol(mean.df)]+0.01)

#calculating tissue means from Cambuli et al
es_mean=rowMeans(x[,14:15])
ts_mean=rowMeans(x[,16:17])
rna=data.frame(Probe=x$Probe,es_mean,ts_mean)
rna[,2:3]=log2(rna[,2:3]+0.01)
colnames(rna)[1]="Gene_Name"




##Stitching the Gingeras and Cambuli datasets together

in.es=cross.look[cross.look$Gene_Name%in%rna$Gene_Name,]
in.ging=in.es[in.es$ENSMBL_ID%in%mean.df$ENSMBL_ID,]
in.both=unique(in.ging)



mer=unique(merge(in.both,mean.df,by="ENSMBL_ID")[,c(1,3:(ncol(mean.df)+2))])
mer2=unique(merge(mer,rna,by="Gene_Name"))


###Normalising the datasets based on ranked positions###
ref.rank = rank(mer2$es_mean,ties='first')
mer.norm = mer2
for (i in 3:ncol(mer2)) {
  rank.match = match(rank(mer2[,i],ties='first'),ref.rank)
  mer.norm[,i] = mer2$es_mean[rank.match]
}



##Generating list of Gene IDs which are REDE/NEDE only interacting

es.rede.ids=es.gene.look$Gene_ID[es.gene.look$ESC_REDE>0&es.gene.look$ESC_NEDE==0]
es.nede.ids=es.gene.look$Gene_ID[es.gene.look$ESC_REDE==0&es.gene.look$ESC_NEDE>0]
ts.rede.ids=ts.gene.look$Gene_ID[ts.gene.look$TSC_REDE>0&ts.gene.look$TSC_NEDE==0]
ts.nede.ids=ts.gene.look$Gene_ID[ts.gene.look$TSC_REDE==0&ts.gene.look$TSC_NEDE>0]
all.ids=unique(es.gene.look$Gene_ID,ts.gene.look$Gene_ID)


##Function for getting median values of expression for each class within each tissue
ids=es.rede.ids
get.tissue.medians=function(ids,class){
df.sub=mer.norm[mer.norm$Gene_Name%in%ids,3:ncol(mer.norm)]
tissue.medians=c()
for(i in 1:ncol(df.sub)){
  tissue.medians[i]=median(df.sub[,i])
  }
fun.df=data.frame(Tissue=colnames(df.sub),Median.exp=tissue.medians,Class=rep(class))
return(fun.df)}

es.rede.medians=get.tissue.medians(ids=es.rede.ids,class="ES_REDE")
es.nede.medians=get.tissue.medians(ids=es.nede.ids,class="ES_NEDE")
ts.rede.medians=get.tissue.medians(ids=ts.rede.ids,class="TS_REDE")
ts.nede.medians=get.tissue.medians(ids=ts.nede.ids,class="TS_NEDE")
all.medians=get.tissue.medians(ids=all.ids,class="All")





es.tog=rbind(es.rede.medians,es.nede.medians,all.medians)
es.tog$Tissue=factor(es.tog$Tissue,levels=ging.order$V1)
ts.tog=rbind(ts.rede.medians,ts.nede.medians,all.medians)
ts.tog$Tissue=factor(ts.tog$Tissue,levels=ging.order$V1)

##Ploting median expression values as shown in Figure 3 D

ggplot(es.tog,aes(x=Tissue,y=Median.exp,colour=Class))+geom_point()
ggplot(ts.tog,aes(x=Tissue,y=Median.exp,colour=Class))+geom_point()

