####Inputs####
##set workdirectory
setwd("~/todd/Data/Homer_analysis")

##path to bedtools
homer = '~/Homer/bin/'

##import functions
source('~/todd/Functions/annotateTrend.R')

#Regions for trend plot as generated by Putting_together_beds_into_ROI.R
ROI=read.delim("~/todd/Data/Output/ROI_coord.txt")

##Set flank to plot trend either side of midpoint for each ROI
flank=1500

#HomerTag Directory
tag.dir="~/chris/Homer_Tags/"

##tag list - ChIP/ATAC-seq data to be analysed/plotted
tag.names=c("ES_H3K4me1","ES_H3K27ac","ES_Nanog","ES_Oct4","ES_Sox2","ES_ATAC","TS_H3K4me1","TS_H3K27ac","TS_Cdx2","TS_Elf5","TS_Eomes","TS_ATAC")


####Script####
classes=as.character(unique(ROI[,9]))
##generate trend plot files for each class
for(i in 1:length(classes)){
  class.bed=ROI[ROI$class==classes[i],1:4]
  mid=round((class.bed[,2]+class.bed[,3])/2)
  class.bed[,2]=mid-flank
  class.bed[,3]=mid+flank
  #temporary file of bed coordinates 
  temp.bed = tempfile()
  write.table(class.bed,file=temp.bed,quote=F,sep='\t',col.names=F,row.names=F)
  
  ##for each ChIP/ATAC dataset in the list apply the Homer annotateTrend function
  for(n in 1:length(tag.names)){
    tag=paste(tag.dir,tag.names[n],sep="")
    ann.tag=annotatetrend(bed.file=temp.bed,tag=tag,path.to.homer=homer)
    #combine into a single data frame
    if(n==1){df=ann.tag[,1:2]}else{df=cbind(df,ann.tag[,2])}
    colnames(df)[1+n]=tag.names[n]
    
  }
  colnames(df)[1]="Position"
  ##Output to a file for non-R based plotting if desired
  write.table(df,paste(classes[i],"_trends.txt",sep=""),sep = "\t",quote = F,col.names = T,row.names = F)
  unlink(temp.bed)
  
  ##plot trends##
  x=df
  position=x$Position
  x=x[,2:ncol(x)]
  xrange=range(0,1)
  yrange=c(0,100)
  pdf(paste(classes[i],"_trends_plot.pdf",sep=""),width = 4,height = 4)
  plot(xrange,yrange,type="n",xlab="Position",ylab="Signal")
  colour=rainbow(ncol(x))
  for(i in 1:ncol(x)){
    lines(position,x[,i],col=colour[i])}
  legend(xrange[1],yrange[2],colnames(x),col=colour,cex=0.8,lty=1)
  dev.off()
  
}
