####Inputs####
#set working directory
setwd("~/todd/Motif_analysis/")

#Hocomoco FIMO analysis directory
directory=c("./hocomoco/")

##Files for Enhancer and Non-Enhancer TE coordinates
es.enh=read.delim("~/todd/Data/Output/ESC_enhancer_TEs.txt",h=F)
ts.enh=read.delim("~/todd/Data/Output/TSC_enhancer_TEs.txt",h=F)
non.enh=read.delim("~/todd/Data/Output/NonEnhTE_candidates.txt")

#R packages
library(RColorBrewer)
library(scales)
library(ggplot2)


####Script####

for(type in c("ESC","TSC")){
  #ESC and TSC TE classes of interest
  if(type == "ESC"){rltr.list=c("RLTR9E","RLTR9D","RLTR9A3","RLTR13D6")}
  if(type == "TSC"){rltr.list=c("RTR13B1","RLTR13B2","RLTR13B3","RLTR13B4","RLTR13D5")}
  #ESC and TSC TFs of interest within HOCOMOCO database
  if(type == "ESC"){int.ids=c("ERR2","PO5F1","CTCF_","SOX2","NANOG","KLF4")}
  if(type == "TSC"){int.ids=c("CDX2","ERR2","CTCF_","ELF5")}
  
  enh=rbind(es.enh,ts.enh)
  

get.percentage.df=function(class,cutoff){
  #load fasta sequences of Enhancer and NonEnhancer TEs
  fa = scan(paste(directory,class,"_enh.fa",sep=""),sep='\n', character())
  enh.id=gsub(">","",fa[grep(">",fa)])
  fa = scan(paste(directory,class,"_non.fa",sep=""),sep='\n', character())
  non.id=gsub(">","",fa[grep(">",fa)])
  
  #load FIMO results for TE class as generated by Clustal_and_Motif_analysis.R
  fimo.enh=read.delim(paste(directory,class,"_enh_fimo.txt",sep=""))
  fimo.non=read.delim(paste(directory,class,"_non_fimo.txt",sep=""))
  
  tog.fimo=rbind(fimo.enh,fimo.non)
  tog.fimo$motif_alt_id=tog.fimo$X..motif_id
  #getting a list of Motifs present in FIMO analysis
  fimo.ids=unlist(unique(tog.fimo$motif_alt_id))
  
  #For each motif look to see if present for each element within the TE class
  for(i in 1:length(fimo.ids)){
    id=fimo.ids[i]
    fimo.sub=tog.fimo[tog.fimo$motif_alt_id==id,]  
    id.match=(enh.id %in% fimo.sub$sequence_name)*1
    if(i==1){df=data.frame(id=enh.id,TF=id.match)}else{df=cbind(df,id.match)}
  }
  colnames(df)=c("ID",fimo.ids)
  enh.df=df
  for(i in 1:length(fimo.ids)){
    id=fimo.ids[i]
    fimo.sub=tog.fimo[tog.fimo$motif_alt_id==id,]  
    id.match=(non.id %in% fimo.sub$sequence_name)*1
    if(i==1){df2=data.frame(id=non.id,TF=id.match)}else{df2=cbind(df2,id.match)}
  }
  colnames(df2)=c("ID",fimo.ids)
  non.df=df2
  
  ##Calculate the percentage of elements containing each motif
  sum.enh=colSums(enh.df[,2:ncol(enh.df)])
  sum.non=colSums(non.df[,2:ncol(non.df)])
  
  per.enh=(sum.enh/length(enh.id))*100
  per.non=(sum.non/length(non.id))*100
  per.diff=per.enh-per.non
  
  df=data.frame(per.enh,per.non,per.diff,fimo.ids)
  
  
  #load AME data for class as generated by Clustal_and_Motif_analysis.R
  ame=read.delim(paste(directory,class,"_ame.txt",sep=""))
  if(nrow(ame)>7){
    ame=as.character(ame[8:nrow(ame),1])
    ame.id=unlist(lapply(strsplit(ame,split = " "),function(x){x[8]}))
    ame.pval=as.numeric(unlist(lapply(strsplit(ame,split = " |)"),function(x){x[length(x)]})))
    ame.df=data.frame(id=ame.id,pval=ame.pval)}else{
      ame.df=data.frame(id="null",pval="1")
    }
  
  #get p values from AME analysis
  pval=c()
  for(n in 1:nrow(df)){
    id=as.character(df[n,4])
    ame.sub=ame.df[ame.df$id==id,]  
    if(nrow(ame.sub)==0){pval[n]=1}else{pval[n]=ame.sub[1,2]}
  }
  df$pval=pval
  
  return(df)}

for(i in 1:length(rltr.list)){
  class=rltr.list[i]
  
  df=get.percentage.df(class)
  df$FC=(df$per.enh+0.01)/(df$per.non+0.01)
  
  #determine if motif should be labelled by significance
  label=c()
  for(n in 1:nrow(df)){
    sub=df[n,]
    if(sub$FC>2&sub$per.enh>40&sub$pval<0.05){label[n]=as.character(sub$fimo.ids)}else{label[n]=""}
  }
  
  df$label=label

  label2=c()
  for(n in 1:nrow(df)){
    sub=df[n,]
    if(grepl(paste(int.ids,collapse = "|"),x=sub$fimo.ids)){label2[n]=as.character(sub$fimo.ids)}else{label2[n]=""}
  }
  df$label2=label2

  ##Plot motif percentages Enh vs NonEnh
  pdf(paste(class,"_motif_percentages_hocomoco.pdf",sep=""),width = 6,height = 6)
  gg=ggplot(df,aes(x=per.enh,y=per.non,col=as.factor(df$FC>2&df$per.enh>40&df$pval<0.05)))+geom_point()+ggtitle(class)+
    geom_abline(slope = 1,intercept = c(0,0),linetype=2,colour="red")+coord_cartesian(ylim=c(0,100),xlim=c(0,100))+
    expand_limits(x = 0, y = 0)+scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0))+
    theme_classic()+theme(legend.position="none",axis.text = element_text(face="bold", size=10),axis.title = element_text(face="bold", size=10), title =element_text(face="bold", size=10) )+
    geom_text(label=df$label2, nudge_x = 0, nudge_y=0,color="black", size=2.5,fontface = "bold")+
    geom_text(label=df$label, nudge_x = 0, nudge_y=0,color="red", size=2.5,fontface = "bold")+labs(x="Percentage of Enhancer Copies",y="Percentage of Non-Enhancer Copies")

  plot(gg)
  dev.off()
}

}
