####Inputs####
#Set working directory
setwd("~/todd/CRISPRi/")

#load R packages
library(ggplot2)

#load functions and path to bedtools
source('~/todd/Functions/intersectBed.R')
bedtools = '~/bedtools2/bin/'

#Peak data for H3K27ac within control sample
H3K27ac.peaks=read.delim("H3K27ac_empty_peaks.broadPeak",h=F)

#Normalised H3K27ac read counts across TEs, included input counts
TE.counts=read.delim("TE_Normalised_H3K27ac_read_counts.txt")

#lookup file for RLTR13D6 elements predicted to be hit as generated by RLTR13D6_lookup_files.R
RLTR.hits=read.delim("RLTR13D6_CRISPRi_hits_lookup.txt")[,c(6,9:10)]

#lookup file for which RLTR13D6 elements interact with genes as generated by RLTR13D6_lookup_files.R
target.look=read.delim("RLTR13D6_target_look.txt")

#Normalised gene expression values as generated by RLTR13D6_DESeq.R
rna=read.delim("RLTR13D6_RNA_vsd.txt")

#HiC data
hic = '~/todd/Data/PCHiC/gothic_interactions_all_xy'


####Script####
TEs.with.peaks=intersectBed(TE.counts[,1:4],H3K27ac.peaks[,1:4],opt.string=" -wa ",path.to.bedtools=bedtools)[,4]
TE.counts$H3K27ac_peak=TE.counts$ID%in%TEs.with.peaks

TE.counts$H3.control=TE.counts$empty_H3K27ac-TE.counts$empty_Input
TE.counts$H3.set1=TE.counts$sg1.4_H3K27ac-TE.counts$empty_Input
TE.counts$H3.set2=TE.counts$sg5.8_H3K27ac-TE.counts$empty_Input

TE.counts$H3.control.log2=log2(TE.counts$H3.control+0.01)
TE.counts$H3.set1.log2=log2(TE.counts$H3.set1+0.01)
TE.counts$H3.set2.log2=log2(TE.counts$H3.set2+0.01)

TE.counts$H3.set1.lfc=TE.counts$H3.set1.log2-TE.counts$H3.control.log2
TE.counts$H3.set2.lfc=TE.counts$H3.set2.log2-TE.counts$H3.control.log2


RLTR13D6.counts=TE.counts[TE.counts$class=="RLTR13D6",c(4,10,14:18)]
RLTR9.counts=TE.counts[TE.counts$class=="RLTR9",c(4,10,14:18)]

RLTR13D6=merge(RLTR13D6.counts,RLTR.hits,by="ID")

##Plot change in H3K27ac levels at RLTR13D6 as seen in Figure 5 A+B

ggplot(RLTR13D6[RLTR13D6$H3K27ac_peak,],aes(y=H3.set1.log2,x=H3.control.log2,colour=as.factor(group1.hits)))+geom_point()+ylim(c(0,8))+xlim(c(0,8))
ggplot(RLTR13D6[RLTR13D6$H3K27ac_peak,],aes(y=H3.set2.log2,x=H3.control.log2,colour=as.factor(group2.hits)))+geom_point()+ylim(c(0,8))+xlim(c(0,8))

ggplot(RLTR9.counts[RLTR9.counts$H3K27ac_peak,],aes(y=H3.set1.log2,x=H3.control.log2))+geom_point()+ylim(c(0,8))+xlim(c(0,8))
ggplot(RLTR9.counts[RLTR9.counts$H3K27ac_peak,],aes(y=H3.set2.log2,x=H3.control.log2))+geom_point()+ylim(c(0,8))+xlim(c(0,8))




colnames(rna)[1]="Gene"
rna$WT.exp=rowMeans(rna[,2:4])
rna$Set1.exp=rowMeans(rna[,8:10])
rna$Set2.exp=rowMeans(rna[,5:7])

rna$Set1.exp.lfc=rna$Set1.exp-rna$WT.exp
rna$Set2.exp.lfc=rna$Set2.exp-rna$WT.exp
rna=rna[,c(1,11:15)]



hic.data<- local({
  load(hic)
  stopifnot(length(ls())==1)
  environment()[[ls()]]
})

es<-hic.data$ESC[hic.data$ES.pp==F,]
es$target.ID = paste(es$chr.target,es$start.target,es$end.target,sep="-")
es$name.bait<-unlist(lapply(strsplit(es$name.bait,split = "-|,"),function(x){x[[1]]}))
es$bait.ID=paste(es$chr.bait,es$start.bait,es$end.bait,sep="-")

es=unique(es[,c("name.bait","bait.ID","target.ID")])
colnames(es)[1]="Gene"

mer=merge(es,target.look,by="target.ID")
mer2=merge(mer,rna,by="Gene")
colnames(mer2)[4]="ID"
mer3=merge(mer2,RLTR13D6,by="ID")

mer3.peaks=mer3[mer3$H3K27ac_peak,]

##Plot change in Gene expression against change in H3K27ac at interacting RLTR13D6 element as seen in Figure 5 figure supplement 2

ggplot(mer3.peaks,aes(x=H3.set1.lfc,y=Set1.exp.lfc,colour=as.factor(group1.hits)))+geom_point()+
  ylim(c(-1,1))+xlim(c(-2.5,2.5))
ggplot(mer3.peaks,aes(x=H3.set2.lfc,y=Set2.exp.lfc,colour=as.factor(group2.hits)))+geom_point()+
  ylim(c(-1,1))+xlim(c(-4,4))
